### ISSUE TITLE
NEC vectorizer: non-obvious vectorization failures

### ISSUE THREAD

**Issue by raver119** [KonduitAI/deeplearning4j#276]
NCC vectorizer can fail on vectorization without clear explanation:

```
#include <stdio.h>
typedef unsigned int uint;
typedef long long Nd4jLong;
void foo(float *array,  Nd4jLong limit) {
 for (uint e = 0; e < limit; e++) {
   array[e] += 512.f;
 }
}
int main() {
   float array[512];
   foo(array,   512LL);
   return 0;
}
```

NCC output:
```
/opt/nec/ve/bin/nc++ -O3 -fno-inline bug_vectorization.cpp
nc++: vec( 103): bug_vectorization.cpp, line 5: Unvectorized loop.
```

but, if you change loop into this:
```
 for (int e = 0; e < limit; e++) {
```

or 

```
 for (auto e = 0; e < limit; e++) {
```

loop is successfully vectorized:

```
/opt/nec/ve/bin/nc++ -O3 -fno-inline bug_vectorization.cpp
nc++: vec( 101): bug_vectorization.cpp, line 5: Vectorized loop.
```

So for some reason use of `uint` breaks vectorization.
Same applies to reduce idioms as well.

**Comment by raver119** [comment]
cc @mikishin ^^^

**Comment by Y-Shibuya** [comment]
We received an answer from the development team.

- In the case of an unsigned int loop control variable, when the variable overflows an integer overflow, it returns to 0 and the reference starts from the beginning of the array.
- So we decided that there was a non-vectorizable dependency. This is fixing the compiler to be vectorizable.

**Comment by raver119** [comment]
Right, we've understood that was the case, and what was the workaround. Problem is the fact it wasn't clear without experiments. Some message coming out of compiler would be helpful here.
