### ISSUE TITLE
NEC vectorizer problem with big methods

### ISSUE THREAD

**Issue by raver119** [KonduitAI/deeplearning4j#317]
NCC compiler fails to generate efficient code if method is big enough.

Please consider this code:
https://gist.github.com/raver119/4055136e9fb19e6fb9588b6b94d5194c

In this code, there's 2 important methods: `omp` and `huge`.
By design they implement the same iteration logic with the same parallelism model. The only difference there: `huge` method includes support for more than one rank. So when app is executed - they do the same loop: they rotate over the same 4D array. But time spent for execution is dramatically different:

NCC output:
```
Time small: [62 us]; Time huge: [2443 us]
```

x86 gcc 7.4 output:
```
Time small: [189 us]; Time huge: [195 us]
```

**Comment by raver119** [comment]
cc @mikishin ^^^

**Comment by Y-Shibuya** [comment]
Rerunning with the latest SDK seems to fix the problem.
```
[shibuya@aurora03 issue317]$ /opt/nec/ve/bin/nc++ -O3 -fopenmp  test_big_method.cpp -o  aurora_big_method
......
[shibuya@aurora03 issue317]$ ./aurora_big_method 
Time small: [57 us]; Time huge: [61 us]
```
The Aurora03 environment has been updated, so you can try it out if you like.

**Comment by raver119** [comment]
Oh, that's great news! Thank you very much!
