### ISSUE TITLE
NEC veoffload behaviour is too cryptic

### ISSUE THREAD

**Issue by raver119** [KonduitAI/deeplearning4j#345]
NEC veoffload behaviour isn't really transparent.
Right now, I have binary built with nc++, but when i try to load it and open context - I get an error that gives me no real information about the failure. What was wrong? Why failure happened?

Code used for veoffload init:
```
proc = veo_proc_create(deviceId);     
handle = veo_load_library(proc, veobin); 

if (proc == null) 
    throw new RuntimeException("veo_proc is null");

  if (handle < 1)     
    throw new RuntimeException("handle is [" + handle + "]");


  ctx = veo_context_open(proc);
 if (proc == null || ctx == null)
     throw new RuntimeException("setDevice() failed");
```

i get `setDevice() failed` exception, which means that  `ctx == null` due to `veo_context_open(proc)` failure.

All i get in logs is this:

```
2020-03-24T04:15:32-0400 veos.os_module.core ERROR 30636 Assign failed exception not served PID 69596
2020-03-24T04:15:32-0400 veos.os_module.core ERROR 30636 Assign failed exception not served PID 69598
2020-03-24T04:15:32-0400 veos.os_module.core ERROR 30636 Assign failed exception not served PID 69600
2020-03-24T04:15:32-0400 veos.os_module.core ERROR 30636 Assign failed exception not served PID 69603
2020-03-24T04:15:32-0400 veos.os_module.core ERROR 30636 Assign failed exception not served PID 69605
2020-03-24T04:15:32-0400 veos.os_module.core ERROR 30636 Assign failed exception not served PID 69607
```

Validation tool says binary is ok:
```
[raver119@aurora03 nd4j-tests]$ /opt/nec/ve/bin/ve_validate_binary -f /home/raver119/.javacpp/cache/nd4j-aurora-1.0.0-SNAPSHOT-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libnd4jaurora.so
**VE BINARY/SHARED LIBRARY IS VALIDATED SUCCESSFULLY!!**
```

It would be really nice if error messages would be actually useful for developer, because right now system says nothing about what happened and what developer should do in order to get things fixed.

**Comment by raver119** [comment]
cc @mikishin ^^^

**Comment by raver119** [comment]
Here's the code in C/C++ that reproduces issue:

```
#include <ve_offload.h>
#include <cstdio>
#include <cstddef>
int main()
{
  /* Load "vehello" on VE node 0 */
  struct veo_proc_handle *proc = veo_proc_create(0);
  if (proc == nullptr)
     printf("proc is nullptr\n");

  uint64_t handle = veo_load_library(proc, "/home/raver119/.javacpp/cache/nd4j-aurora-1.0.0-SNAPSHOT-linux-x86_64.jar/org/nd4j/nativeblas/linux-x86_64/libnd4jaurora.so");

  if (handle == 0)
     printf("handle is 0\n");

  struct veo_thr_ctxt *ctx = veo_context_open(proc);
  if (ctx == nullptr) {
     printf("ctx is nullptr\n");
     return -1;
  }

  veo_context_close(ctx);
  return 0;
}
```

Build cmd line:
```
g++ -o ve_binary ve_binary.cpp -I/opt/nec/ve/veos/include -L/opt/nec/ve/veos/lib64    -Wl,-rpath=/opt/nec/ve/veos/lib64 -lveo -std=c++11
```


Executable output:

```
[raver119@aurora03 ~]$ ./ve_binary 
handle is 0
ctx is nullptr
```

So, something happens, but not quite clearly what exactly happens.

**Comment by Y-Shibuya** [comment]
The development team says that veoffload logging will be enhanced in late May.

https://veos-sxarr-nec.github.io/veoffload/md_GettingStarted.html
By using the method described here, debug information can be output by outputting a debug log using the .log4crc file.
However, we do not know how to read the log file, so we will ask the development team.

**Comment by raver119** [comment]
Thank you very much!

**Comment by Y-Shibuya** [comment]
As a result of investigation by the development team, it is an error that a module that does not include -fPIC in the compile option is linked.

I will report to the development team that it is difficult to understand the cause of the error.

**Comment by raver119** [comment]
Thank you, we'll check it out immediately.

**Comment by raver119** [comment]
Yep, thanks for help, that's it. Hope dev team will be able to improve logging for such cases.
