### ISSUE TITLE
NEC gdb -tui mode

### ISSUE THREAD

**Issue by quickwritereader** [KonduitAI/deeplearning4j#543]
I need gdb -tui mode enabled. It helps a lot with debugging.

**Comment by quickwritereader** [comment]
cc @mikishin

**Comment by saudet** [comment]
@mikishin Apparently, we only need to recompile GDB with `-enable-tui`. Are you using a standard version of GDB?

**Comment by Y-Shibuya** [comment]
I created an rpm with "-enable-tui" set from the source rpm of GDB for Aurora.

The rpm is not supported by the development team. Should I install it in the Aurora03 environment?

**Comment by quickwritereader** [comment]
@Y-Shibuya 
yes, please do. we need it on aurora03
thank you very much.

**Comment by Y-Shibuya** [comment]
I have installed rpm on Aurora 03.
